-- +goose Up
ALTER TABLE service_orders
    ADD COLUMN IF NOT EXISTS wallet_hold DECIMAL(10,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS wallet_hold_id UUID;


-- -- +goose Up
-- -- Full services schema migration (safe rebuild)

-- -------------------------------------------------------
-- -- SERVICE CATEGORIES
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_categories (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     icon_url VARCHAR(500),
--     banner_image VARCHAR(500),
--     is_active BOOLEAN DEFAULT TRUE,
--     sort_order INT DEFAULT 0,
--     highlights TEXT[] DEFAULT '{}',
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- ALTER TABLE service_categories
--     ADD COLUMN IF NOT EXISTS highlights TEXT[] DEFAULT '{}';

-- -------------------------------------------------------
-- -- SERVICE TABS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_tabs (
--     id SERIAL PRIMARY KEY,
--     category_id INT NOT NULL REFERENCES service_categories(id) ON DELETE CASCADE,
--     name VARCHAR(255) NOT NULL,
--     description TEXT,
--     icon_url VARCHAR(500),
--     banner_title VARCHAR(255),
--     banner_description VARCHAR(500),
--     banner_image VARCHAR(500),
--     is_active BOOLEAN DEFAULT TRUE,
--     sort_order INT DEFAULT 0,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- SERVICES
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS services (
--     id SERIAL PRIMARY KEY,
--     category_id INT NOT NULL REFERENCES service_categories(id) ON DELETE CASCADE,
--     tab_id INT NOT NULL REFERENCES service_tabs(id) ON DELETE CASCADE,
--     name VARCHAR(255) NOT NULL,
--     description TEXT NOT NULL,
--     image_url VARCHAR(500),
--     base_price DECIMAL(10,2) NOT NULL,
--     original_price DECIMAL(10,2),
--     discount_percentage INT DEFAULT 0,
--     pricing_model VARCHAR(50) DEFAULT 'fixed',
--     base_duration_minutes INT NOT NULL,
--     max_quantity INT DEFAULT 1,
--     is_active BOOLEAN DEFAULT TRUE,
--     is_featured BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- ADD-ON SERVICES
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS addon_services (
--     id SERIAL PRIMARY KEY,
--     category_id INT NOT NULL REFERENCES service_categories(id) ON DELETE CASCADE,
--     title VARCHAR(255) NOT NULL,
--     description TEXT,
--     image_url VARCHAR(500),
--     price DECIMAL(10,2) NOT NULL,
--     original_price DECIMAL(10,2),
--     duration_minutes INT DEFAULT 0,
--     is_active BOOLEAN DEFAULT TRUE,
--     sort_order INT DEFAULT 0,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- SERVICE OPTIONS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_options (
--     id SERIAL PRIMARY KEY,
--     service_id INT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
--     name VARCHAR(255) NOT NULL,
--     type VARCHAR(50) NOT NULL,
--     is_required BOOLEAN DEFAULT FALSE,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- OPTION CHOICES
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_option_choices (
--     id SERIAL PRIMARY KEY,
--     option_id INT NOT NULL REFERENCES service_options(id) ON DELETE CASCADE,
--     label VARCHAR(255) NOT NULL,
--     price_modifier DECIMAL(10,2) DEFAULT 0,
--     duration_modifier_minutes INT DEFAULT 0,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- SERVICE PROVIDERS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_providers (
--     id UUID PRIMARY KEY,
--     user_id UUID UNIQUE NOT NULL,
--     photo VARCHAR(500),
--     rating DECIMAL(3,2) DEFAULT 0,
--     status VARCHAR(50) DEFAULT 'offline',
--     is_verified BOOLEAN DEFAULT FALSE,
--     total_jobs INT DEFAULT 0,
--     completed_jobs INT DEFAULT 0,
--     last_active TIMESTAMP,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- SERVICE ORDERS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS service_orders (
--     id UUID PRIMARY KEY,
--     code VARCHAR(50) UNIQUE NOT NULL,
--     user_id UUID NOT NULL,
--     provider_id UUID,
--     status VARCHAR(50) NOT NULL,
--     address TEXT NOT NULL,
--     latitude DECIMAL(10,8),
--     longitude DECIMAL(11,8),
--     service_date TIMESTAMP NOT NULL,
--     frequency VARCHAR(50) DEFAULT 'once',
--     quantity_of_pros INT DEFAULT 1,
--     hours_of_service DECIMAL(5,2) DEFAULT 1.0,
--     subtotal DECIMAL(10,2) NOT NULL,
--     discount DECIMAL(10,2) DEFAULT 0,
--     surge_fee DECIMAL(10,2) DEFAULT 0,
--     platform_fee DECIMAL(10,2) DEFAULT 0,
--     total DECIMAL(10,2) NOT NULL,
--     coupon_code VARCHAR(50),
--     notes TEXT,
--     wallet_hold DECIMAL(10,2) DEFAULT 0,
--     wallet_hold_id UUID,
--     created_at TIMESTAMP DEFAULT NOW(),
--     accepted_at TIMESTAMP,
--     started_at TIMESTAMP,
--     completed_at TIMESTAMP,
--     cancelled_at TIMESTAMP
-- );

-- -------------------------------------------------------
-- -- ORDER ITEMS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS order_items (
--     id SERIAL PRIMARY KEY,
--     order_id UUID NOT NULL REFERENCES service_orders(id) ON DELETE CASCADE,
--     service_id INT NOT NULL REFERENCES services(id),
--     service_name VARCHAR(255) NOT NULL,
--     base_price DECIMAL(10,2) NOT NULL,
--     calculated_price DECIMAL(10,2) NOT NULL,
--     duration_minutes INT NOT NULL,
--     selected_options JSONB,
--     created_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- ORDER ADD-ON
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS order_add_ons (
--     id SERIAL PRIMARY KEY,
--     order_id UUID NOT NULL REFERENCES service_orders(id) ON DELETE CASCADE,
--     add_on_id INT NOT NULL REFERENCES addon_services(id),
--     title VARCHAR(255) NOT NULL,
--     price DECIMAL(10,2) NOT NULL,
--     created_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- RATINGS
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS ratings (
--     id UUID PRIMARY KEY,
--     order_id UUID NOT NULL UNIQUE REFERENCES service_orders(id) ON DELETE CASCADE,
--     user_id UUID NOT NULL,
--     provider_id UUID NOT NULL,
--     score INT NOT NULL CHECK (score >= 1 AND score <= 5),
--     comment TEXT,
--     created_at TIMESTAMP DEFAULT NOW()
-- );

-- -------------------------------------------------------
-- -- SURGE ZONES
-- -------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS surge_zones (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     surge_multiplier DECIMAL(3,2) DEFAULT 1.00,
--     is_active BOOLEAN DEFAULT TRUE,
--     valid_from TIMESTAMP,
--     valid_to TIMESTAMP,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );
